"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Admin_1 = require("../Controleur/Admin");
exports.Administrateur = Admin_1.Administrateur;
var Acceuil_1 = require("../Controleur/Acceuil");
exports.Acceuil = Acceuil_1.Acceuil;
var Details_1 = require("../Controleur/Details");
exports.detail = Details_1.detail;
var AjoutPanier_1 = require("./AjoutPanier");
exports.ajoutPanier = AjoutPanier_1.ajoutPanier;
